---
title: "Variant Overlap"
author: '`r Sys.info()[["user"]] `'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    css: styles.css
    df_print: kable
    keep_md: yes
    number_sections: yes
    toc: yes
    mathjax: null
    # theme: null
    # highlight: null
params:
  input_files: 
    - variants1.tsv
    - variants2.tsv
  id_colnames:
    - Chromosome
    - Start_Position
    - End_Position
    - Reference_Allele
    - Tumor_Seq_Allele2
    - Tumor_Sample_Barcode
    - Matched_Norm_Sample_Barcode
  output_dir: output
---
```{r setup, include=FALSE}
library("ggplot2")
library("knitr")
library("DT")
source("overlap.R")

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.height = 12)
knitr::opts_chunk$set(fig.width = 12)

input_files <- params$input_files
output_dir <- params$output_dir
id_colnames <- params$id_colnames

load_variants <- function(filename, id_colnames){
  # load the variants from a tab-delimited file with headers
  # need to load as colClasses = "character" because otherwise whitespace gets inserted later with paste
  df <- read.delim(
    file = filename, 
    header = TRUE, 
    sep = '\t', 
    comment.char = '#',
    check.names = FALSE, 
    colClasses = "character")
  
  # add a unique label
  df[["VariantID"]] <- apply(df[,id_colnames], MARGIN = 1, FUN = paste0, collapse = ':')
  
  return(df)
}

# load datasets
input_list <- list()
for(i in input_files){
  input_list[[i]] <- load_variants(i, id_colnames)
}

# create variant lists
variant_list <- list()
for(name in names(input_list)){
  variant_list[[name]] <- input_list[[name]][["VariantID"]]
}

# overlap the datasets
overlaps <- create_overlaps(variant_list, 
                            col_name = "VariantID", 
                            overlap_prefix = '',
                            comb_delim = '_')

# aggregate results metrics
aggr_table <- aggregate_overlaps(overlaps)

# save output files
# get the variants unique to each file; comb == name
for(name in names(input_list)){
  output_filename <- sprintf("%s.uniq.tsv", name)
  output_path <- file.path(output_dir, output_filename)
  uniq_variantID_df <- overlaps[overlaps[["comb"]] == name ,]
  uniq_df <- merge(x = input_list[[name]], y = uniq_variantID_df, by = "VariantID")
  write.table(x = uniq_df, file = output_path, quote = FALSE, sep = '\t', row.names = FALSE, col.names = TRUE)
}

# TODO: how to handle outputting the variants from the overlap combinations?
# get the variants from all other combinations
for(name in unique(overlaps[["comb"]])){
  if(! name %in% names(input_list)){
    print(name)
    output_filename <- sprintf("%s.tsv", name)
    output_path <- file.path(output_dir, output_filename)

    common_variant_IDs <- overlaps[overlaps[["comb"]] == name, "VariantID"]
    df <- Reduce(function(x, y){
      merge(x[x[["VariantID"]] %in% common_variant_IDs, c(id_colnames, "VariantID")], 
            y[y[["VariantID"]] %in% common_variant_IDs, c(id_colnames, "VariantID")], 
            all = TRUE) # by = "VariantID",
      }, input_list)
    write.table(x = df, file = output_path, quote = FALSE, sep = '\t', row.names = FALSE, col.names = TRUE)
  }
}

```

# Input Files
```{r, results='asis'}
for(i in input_files){
  cat(sprintf('\n- %s\n\n', i))
}
cat('Matching on columns:\n\n')
cat(paste0(sprintf('- %s\n\n', id_colnames), collapse = ''))
```

# Overlap

## Metrics

Overlap metrics

```{r}
aggr_table
```

```{r}
overlap_barplot(aggr_table, plot_title = "Number of overlaps per combination")
```


```{r}
save.image()
```